#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("mRides_app.Resource", IsApplication=true)]

namespace mRides_app
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Pref_Gender = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fbLogin = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mRidesLogo = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int button1 = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int buttonBack = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int buttonDone = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int radioButtonHandicap = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int radioButtonLuggage = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int radioButtonNoHandicap = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int radioButtonNoLuggage = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int radioButtonNoPet = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int radioButtonNonSmoker = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public const int radioButtonPet = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int radioButtonSmoker = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int spinnerGender = 2131099667;
			
			// aapt resource value: 0x7f060005
			public const int tableLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int tableRowGender = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int tableRowHandicap = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int tableRowLuggage = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int tableRowSmoker = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int textViewGenderPref = 2131099666;
			
			// aapt resource value: 0x7f060003
			public const int textViewHi = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int textViewSetYourPreferences = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Preferences = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000f
			public const int Back = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int Done = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Hi = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int Pref_Female = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int Pref_Handicap = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int Pref_Luggage = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int Pref_Male = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int Pref_NoHandicap = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int Pref_NoLuggage = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int Pref_NoPet = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int Pref_NonSmoker = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int Pref_Pet = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int Pref_Smoker = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int Prompt_Gender = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int SetYourPreferences = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
