var namespacem_rides__app_1_1_tasks_1_1_callbacks =
[
    [ "IOnFindMatchCompleteCallback", "interfacem_rides__app_1_1_tasks_1_1_callbacks_1_1_i_on_find_match_complete_callback.html", "interfacem_rides__app_1_1_tasks_1_1_callbacks_1_1_i_on_find_match_complete_callback" ],
    [ "IOnGetReviewsAverageCompleteCallback", "interfacem_rides__app_1_1_tasks_1_1_callbacks_1_1_i_on_get_reviews_average_complete_callback.html", "interfacem_rides__app_1_1_tasks_1_1_callbacks_1_1_i_on_get_reviews_average_complete_callback" ]
];